sudo: false
language: node_js
node_js:
- lts/*
services:
- docker
os:
- osx
- linux
before_install:
- |
  if [ $TRAVIS_OS_NAME == "linux" ]; then
    export DISPLAY=':99.0'
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    sudo apt-get install libsecret-1-dev
  fi
install:
- npm install
- npm install -g vsce
script:
- npm run tslint
- npm run compile
- node scripts/genAiKey.js
- echo "y" | vsce package
- npm test --silent
- |
  if [ $TRAVIS_OS_NAME == "linux" ]; then
    docker run -ti --rm -v $PWD:/mnt:ro dkhamsing/awesome_bot --allow-dupe --allow-redirect --skip-save-results `ls *.md` --white-list gitter.im
  fi
deploy:
- provider: releases
  skip_cleanup: true
  api_key: "$GIT_TOKEN"
  file_glob: true
  file: "*.vsix"
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME == linux"
- provider: script
  skip_cleanup: true
  script: vsce publish -p $VSCE_TOKEN --packagePath *.vsix
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME == linux && $TRAVIS_TAG =~ $ISPRODTAG"
env:
  global:
  - ISPRODTAG=^v?[0-9]+\.[0-9]+\.[0-9]+$
  - secure: cqFE5WyytjNXbmAAAXHk/TeUY31I6dbNvplejCS2aYkqjKsVCxtAYajwe7F608GAqeckC17oV6x1ONJs8CJXWlLsMBL9+35TPPzW2LsCSzODm4v64UauEmyFRknC3EuAOzEyZE1/iSP59ZVKUGsA35ac3X69334a25FGVczczOZKuAnrhbWF0AILf4MSa29VvNPsw1VO6SBHjvbE/jBvToGXIc7FmBvmkx9uqM7wHCYgZt37FnF3Rzil1hmHMIvuPIyrkYFhNVruaxv5pYSsCdy7+9SINEzW69SJtzWHEYg/Phv4IbsZfI75Bfau/1H0RDDZacZuMPGw9K9kszOo0VIm53/50kqTUJXaDz+rVBSLauGO49D5kxET6S+PbTzS9cE5Bu/xmkW7J6BlDzG09IoDxtfcgBn+xEW65It1h33OiCHMvU0AXqbjA4b+AveQFkfh5zymPlUOGQNGiqLNEI58eAkfJfSHtUlL3FxSdVgytWCXtA0n/2CioZTcDDQe/YnuE9xvCDJiE7oc+T9RejmH0D5t38BvyuofDq1pIwFwzWYgiCJrlFavl7pZisRL5k4hENBKrLt0Rw/4ByuM0x/K/BSzyNJJOm6vfCqEHS2hz30HhBevnmQXfuftT0hhBQNZpMAMWukdz4oh1tFQomJWB/rv3B6eWo7ut7UyVSw=
